### ISSUE TITLE
Error: Malformed UTF-8 data

### ISSUE THREAD

**Issue by lanlin** [tatumio/tatum-kms#48]
```shell
Error: Malformed UTF-8 data
    at Object.stringify (/usr/src/app/node_modules/crypto-js/core.js:523:24)
    at WordArray.init.toString (/usr/src/app/node_modules/crypto-js/core.js:278:38)
    at getManagedWallets (/usr/src/app/dist/management.js:47:67)
    at Timeout._onTimeout (/usr/src/app/dist/signatures.js:281:68)
```

both docker KMS image (`docker pull tatumio/tatum-kms`) and 
npm installed (`GitHub master branch`) KMS have the same error, 
when running in daemon mode after calling the `generatemanagedwallet BSC` method to add a managed wallet address

**Comment by lanlin** [comment]
after clear the `wallet.dat` file:

```shell
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getManagedWallets (/usr/src/app/dist/management.js:47:26)
    at Timeout._onTimeout (/usr/src/app/dist/signatures.js:281:68)
```

**Comment by lanlin** [comment]
after delete the `wallet.dat` file:

```shell
2022-09-28T07:51:47.932Z - Getting pending transaction from BSC for wallets .
{
  "error": "No such wallet file."
}
```

**Comment by lanlin** [comment]
so, what should I do to add managed wallets and start the KMS?

**Comment by lanlin** [comment]
solved. kms password error.
